export const generateLegalReport = (history) => {
  // Filter out welcome messages and system prompts
  const meaningfulHistory = history.filter(msg =>
    msg.content.length > 50 &&
    !msg.content.includes("Namaste Aryan") &&
    !msg.content.includes("New Case File Opened")
  );

  const userQueries = meaningfulHistory.filter(msg => msg.role === 'user').map(msg => msg.content);
  const aiResponses = meaningfulHistory.filter(msg => msg.role === 'ai').map(msg => {
    // Strip markdown links [text](url) -> text
    return msg.content.replace(/\[(.*?)\]\(.*?\)/g, '$1');
  });

  const date = new Date().toLocaleDateString('en-IN', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
  const time = new Date().toLocaleTimeString('en-IN');
  const refNo = `NS-${Math.floor(Math.random() * 1000000)}`;

  const reportHTML = `
    <html>
      <head>
        <title>NyayaSahayak Legal Report - ${refNo}</title>
        <style>
          body { font-family: 'Times New Roman', serif; padding: 40px; max-width: 800px; margin: 0 auto; line-height: 1.6; color: #000; }
          .header { text-align: center; border-bottom: 2px solid #000; padding-bottom: 20px; margin-bottom: 30px; }
          .logo { font-size: 24px; font-weight: bold; text-transform: uppercase; letter-spacing: 2px; }
          .sub-logo { font-size: 14px; font-style: italic; margin-top: 5px; }
          .meta { display: flex; justify-content: space-between; margin-bottom: 30px; font-size: 14px; border-bottom: 1px solid #ccc; padding-bottom: 10px; }
          .section { margin-bottom: 30px; }
          .section-title { font-weight: bold; text-decoration: underline; margin-bottom: 15px; font-size: 16px; text-transform: uppercase; }
          .content { margin-bottom: 15px; text-align: justify; }
          .query-block { background: #f0f0f0; padding: 10px; border-left: 3px solid #555; margin-bottom: 10px; font-style: italic; }
          .response-block { margin-bottom: 20px; }
          .footer { margin-top: 60px; text-align: center; font-size: 12px; border-top: 1px solid #000; padding-top: 20px; }
          .watermark { position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%) rotate(-45deg); font-size: 100px; color: rgba(0,0,0,0.03); z-index: -1; pointer-events: none; }
          .disclaimer { font-size: 10px; color: #666; margin-top: 30px; text-align: justify; border-top: 1px dotted #ccc; padding-top: 10px; }
        </style>
      </head>
      <body>
        <div class="watermark">CONFIDENTIAL</div>
        
        <div class="header">
          <div class="logo">NyayaSahayak Legal Aid</div>
          <div class="sub-logo">Automated Legal Assessment System</div>
        </div>

        <div class="meta">
          <div><strong>Date:</strong> ${date} | ${time}</div>
          <div><strong>Ref No:</strong> ${refNo}</div>
        </div>

        <div class="section">
          <div class="section-title">I. Subject Matter</div>
          <div class="content">
            Legal assessment regarding: <strong>${userQueries[0] ? userQueries[0].substring(0, 100) + "..." : "General Legal Inquiry"}</strong>
          </div>
        </div>

        <div class="section">
          <div class="section-title">II. Detailed Analysis</div>
          ${aiResponses.map((r, i) => `
            <div class="response-block">
              <div class="query-block">Query: ${userQueries[i] || "Follow-up"}</div>
              <div class="content">${r.replace(/\n/g, '<br>')}</div>
            </div>
          `).join('')}
        </div>

        <div class="section">
          <div class="section-title">III. Recommended Course of Action</div>
          <div class="content">
            Based on the analysis above, the petitioner is advised to follow the procedural steps outlined in the relevant sections. Immediate preservation of evidence and filing of formal complaints (FIR/Writ) where applicable is recommended.
          </div>
        </div>

        <div class="footer">
          <p>Generated by NyayaSahayak AI</p>
          <br><br>
          <p>__________________________<br>Authorized Signature (Digital)</p>
        </div>

        <div class="disclaimer">
          <strong>DISCLAIMER:</strong> This document is generated by an AI Legal Assistant for informational purposes only. It does not constitute binding legal advice or establish an attorney-client relationship. The user is strongly advised to consult a qualified legal practitioner before taking any legal action. NyayaSahayak assumes no liability for actions taken based on this report.
        </div>

        <script>
          window.print();
        </script>
      </body>
    </html>
  `;

  const printWindow = window.open('', '_blank');
  printWindow.document.write(reportHTML);
  printWindow.document.close();
};
